In [1]:
import numpy as np

In [2]:
arr = np.arage(1, 10)

AttributeError: module 'numpy' has no attribute 'arage'

In [3]:
arr = np.arange(1, 10)

In [4]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.sqrt(arr)

array([ 1.        ,  1.41421356,  1.73205081,  2.        ,  2.23606798,
        2.44948974,  2.64575131,  2.82842712,  3.        ])

In [6]:
np.log10(arr)

array([ 0.        ,  0.30103   ,  0.47712125,  0.60205999,  0.69897   ,
        0.77815125,  0.84509804,  0.90308999,  0.95424251])

In [8]:
x = np.random.randn(8)
y = np.random.randn(8)

In [9]:
x

array([-0.94088043,  0.50269277,  0.36683065,  0.14114887,  0.44845367,
       -0.26041945,  0.5114642 ,  0.92404709])

In [10]:
y

array([ 0.70757159, -1.57497049, -1.57892406, -1.3576875 ,  1.92584169,
       -0.16903455,  0.80762297,  0.73392908])

In [11]:
np.maximum(x, y)

array([ 0.70757159,  0.50269277,  0.36683065,  0.14114887,  1.92584169,
       -0.16903455,  0.80762297,  0.92404709])